/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_mnt3.h"

bool_t
xdr_fhandle3 (XDR *xdrs, fhandle3 *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->fhandle3_val, (u_int *) &objp->fhandle3_len, FHSIZE3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dirpath3 (XDR *xdrs, dirpath3 *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MNTPATHLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_name3 (XDR *xdrs, name3 *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MNTNAMLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mountstat3 (XDR *xdrs, mountstat3 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mountres3_ok (XDR *xdrs, mountres3_ok *objp)
{
	register int32_t *buf;

	 if (!xdr_fhandle3 (xdrs, &objp->fhandle))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->auth_flavors.auth_flavors_val, (u_int *) &objp->auth_flavors.auth_flavors_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mountres3 (XDR *xdrs, mountres3 *objp)
{
	register int32_t *buf;

	 if (!xdr_mountstat3 (xdrs, &objp->fhs_status))
		 return FALSE;
	switch (objp->fhs_status) {
	case MNT3_OK:
		 if (!xdr_mountres3_ok (xdrs, &objp->mountres3_u.mountinfo))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_mountlist3 (XDR *xdrs, mountlist3 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct mountbody3), (xdrproc_t) xdr_mountbody3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mountbody3 (XDR *xdrs, mountbody3 *objp)
{
	register int32_t *buf;

	 if (!xdr_name3 (xdrs, &objp->ml_hostname))
		 return FALSE;
	 if (!xdr_dirpath3 (xdrs, &objp->ml_directory))
		 return FALSE;
	 if (!xdr_mountlist3 (xdrs, &objp->ml_next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_groups3 (XDR *xdrs, groups3 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct groupnode3), (xdrproc_t) xdr_groupnode3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_groupnode3 (XDR *xdrs, groupnode3 *objp)
{
	register int32_t *buf;

	 if (!xdr_name3 (xdrs, &objp->gr_name))
		 return FALSE;
	 if (!xdr_groups3 (xdrs, &objp->gr_next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_exports3 (XDR *xdrs, exports3 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct exportnode3), (xdrproc_t) xdr_exportnode3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_exportnode3 (XDR *xdrs, exportnode3 *objp)
{
	register int32_t *buf;

	 if (!xdr_dirpath3 (xdrs, &objp->ex_dir))
		 return FALSE;
	 if (!xdr_groups3 (xdrs, &objp->ex_groups))
		 return FALSE;
	 if (!xdr_exports3 (xdrs, &objp->ex_next))
		 return FALSE;
	return TRUE;
}
