# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kdnssd': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/solid': '@stable'
    'frameworks/kbookmarks': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/syntax-highlighting': '@stable'
    'libraries/phonon': '@stable'
    'graphics/libkexiv2': '@stable'
    'third-party/kdsoap': '@latest'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'libraries/kdsoap-ws-discovery-client': '@stable'
    'plasma/plasma-activities': '@stable'
    'plasma/plasma-activities-stats': '@stable'
