/* config-runtime.h.  Generated by cmake from config-runtime.h.cmake  */

/*
 * Used for the "KDE" version string in generated man pages.
 * Using the definition from this project so as to be independent of Plasma.
 */
#define KDE_VERSION_STRING "@PROJECT_VERSION@"
