/* config-runtime.h.  Generated by cmake from config-runtime.h.cmake  */

/* Define to 1 if you have the `nice' function. */
#cmakedefine HAVE_NICE 1

/* Define to 1 if you have the <sys/select.h> header file. */
#cmakedefine HAVE_SYS_SELECT_H 1

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/*
 * Used for the "KDE" version string in generated man pages.
 * Using the definition from this project so as to be independent of Plasma.
 */
#define KDE_VERSION_STRING "@PROJECT_VERSION@"
