/* Name: DevicePropGeneralData.cpp

   Description: This file is a part of the Corel File Manager application.

   Author:	Oleg Noskov (olegn@corel.com)

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/

/*
 * NOTE: This source file was created using tab size = 2.
 * Please respect that setting in case of modifications.
 */


/**********************************************************************

	--- Qt Architect generated file ---

	File: DevicePropGeneralData.cpp
	Last generated: Tue Oct 19 12:34:41 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "DevicePropGeneralData.h"

#define Inherited QDialog

#include <qframe.h>

CDevicePropGeneralData::CDevicePropGeneralData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	m_IconLabel = new QLabel( this, "Label_1" );
	m_IconLabel->setGeometry( 10, 10, 60, 40 );
	m_IconLabel->setMinimumSize( 0, 0 );
	m_IconLabel->setMaximumSize( 32767, 32767 );
	m_IconLabel->setFocusPolicy( QWidget::NoFocus );
	m_IconLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_IconLabel->setFontPropagation( QWidget::NoChildren );
	m_IconLabel->setPalettePropagation( QWidget::NoChildren );
	m_IconLabel->setFrameStyle( 0 );
	m_IconLabel->setLineWidth( 1 );
	m_IconLabel->setMidLineWidth( 0 );
	m_IconLabel->QFrame::setMargin( 0 );
	m_IconLabel->setText( "---" );
	m_IconLabel->setAlignment( 289 );
	m_IconLabel->setMargin( -1 );

	m_Name = new QLabel( this, "Label_12" );
	m_Name->setGeometry( 81, 10, 395, 52 );
	m_Name->setMinimumSize( 0, 0 );
	m_Name->setMaximumSize( 32767, 32767 );
	m_Name->setFocusPolicy( QWidget::NoFocus );
	m_Name->setBackgroundMode( QWidget::PaletteBackground );
	m_Name->setFontPropagation( QWidget::NoChildren );
	m_Name->setPalettePropagation( QWidget::NoChildren );
	m_Name->setFrameStyle( 0 );
	m_Name->setLineWidth( 1 );
	m_Name->setMidLineWidth( 0 );
	m_Name->QFrame::setMargin( 0 );
	m_Name->setText( "---" );
	m_Name->setAlignment( 289 );
	m_Name->setMargin( -1 );

	QFrame* qtarch_Frame_4;
	qtarch_Frame_4 = new QFrame( this, "Frame_4" );
	qtarch_Frame_4->setGeometry( 12, 66, 464, 10 );
	qtarch_Frame_4->setMinimumSize( 0, 0 );
	qtarch_Frame_4->setMaximumSize( 32767, 32767 );
	qtarch_Frame_4->setFocusPolicy( QWidget::NoFocus );
	qtarch_Frame_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Frame_4->setFontPropagation( QWidget::NoChildren );
	qtarch_Frame_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_Frame_4->setFrameStyle( 52 );
	qtarch_Frame_4->setLineWidth( 1 );
	qtarch_Frame_4->setMidLineWidth( 0 );
	qtarch_Frame_4->QFrame::setMargin( 0 );

	m_DeviceLabel = new QLabel( this, "Label_13" );
	m_DeviceLabel->setGeometry( 12, 108, 80, 20 );
	m_DeviceLabel->setMinimumSize( 0, 0 );
	m_DeviceLabel->setMaximumSize( 32767, 32767 );
	m_DeviceLabel->setFocusPolicy( QWidget::NoFocus );
	m_DeviceLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_DeviceLabel->setFontPropagation( QWidget::NoChildren );
	m_DeviceLabel->setPalettePropagation( QWidget::NoChildren );
	m_DeviceLabel->setFrameStyle( 0 );
	m_DeviceLabel->setLineWidth( 1 );
	m_DeviceLabel->setMidLineWidth( 0 );
	m_DeviceLabel->QFrame::setMargin( 0 );
	m_DeviceLabel->setText( "Device:" );
	m_DeviceLabel->setAlignment( 289 );
	m_DeviceLabel->setMargin( -1 );

	m_Device = new QLabel( this, "Label_15" );
	m_Device->setGeometry( 102, 107, 375, 20 );
	m_Device->setMinimumSize( 0, 0 );
	m_Device->setMaximumSize( 32767, 32767 );
	m_Device->setFocusPolicy( QWidget::NoFocus );
	m_Device->setBackgroundMode( QWidget::PaletteBackground );
	m_Device->setFontPropagation( QWidget::NoChildren );
	m_Device->setPalettePropagation( QWidget::NoChildren );
	m_Device->setFrameStyle( 0 );
	m_Device->setLineWidth( 1 );
	m_Device->setMidLineWidth( 0 );
	m_Device->QFrame::setMargin( 0 );
	m_Device->setText( "---" );
	m_Device->setAlignment( 289 );
	m_Device->setMargin( -1 );

	m_DriverLabel = new QLabel( this, "Label_16" );
	m_DriverLabel->setGeometry( 12, 136, 60, 18 );
	m_DriverLabel->setMinimumSize( 0, 0 );
	m_DriverLabel->setMaximumSize( 32767, 32767 );
	m_DriverLabel->setFocusPolicy( QWidget::NoFocus );
	m_DriverLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_DriverLabel->setFontPropagation( QWidget::NoChildren );
	m_DriverLabel->setPalettePropagation( QWidget::NoChildren );
	m_DriverLabel->setFrameStyle( 0 );
	m_DriverLabel->setLineWidth( 1 );
	m_DriverLabel->setMidLineWidth( 0 );
	m_DriverLabel->QFrame::setMargin( 0 );
	m_DriverLabel->setText( "Driver:" );
	m_DriverLabel->setAlignment( 289 );
	m_DriverLabel->setMargin( -1 );

	m_Driver = new QLabel( this, "Label_18" );
	m_Driver->setGeometry( 102, 136, 375, 20 );
	m_Driver->setMinimumSize( 0, 0 );
	m_Driver->setMaximumSize( 32767, 32767 );
	m_Driver->setFocusPolicy( QWidget::NoFocus );
	m_Driver->setBackgroundMode( QWidget::PaletteBackground );
	m_Driver->setFontPropagation( QWidget::NoChildren );
	m_Driver->setPalettePropagation( QWidget::NoChildren );
	m_Driver->setFrameStyle( 0 );
	m_Driver->setLineWidth( 1 );
	m_Driver->setMidLineWidth( 0 );
	m_Driver->QFrame::setMargin( 0 );
	m_Driver->setText( "---" );
	m_Driver->setAlignment( 289 );
	m_Driver->setMargin( -1 );

	m_ModelLabel = new QLabel( this, "Label_19" );
	m_ModelLabel->setGeometry( 12, 165, 60, 20 );
	m_ModelLabel->setMinimumSize( 0, 0 );
	m_ModelLabel->setMaximumSize( 32767, 32767 );
	m_ModelLabel->setFocusPolicy( QWidget::NoFocus );
	m_ModelLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_ModelLabel->setFontPropagation( QWidget::NoChildren );
	m_ModelLabel->setPalettePropagation( QWidget::NoChildren );
	m_ModelLabel->setFrameStyle( 0 );
	m_ModelLabel->setLineWidth( 1 );
	m_ModelLabel->setMidLineWidth( 0 );
	m_ModelLabel->QFrame::setMargin( 0 );
	m_ModelLabel->setText( "Model:" );
	m_ModelLabel->setAlignment( 289 );
	m_ModelLabel->setMargin( -1 );

	m_Model = new QLabel( this, "Label_20" );
	m_Model->setGeometry( 102, 165, 375, 20 );
	m_Model->setMinimumSize( 0, 0 );
	m_Model->setMaximumSize( 32767, 32767 );
	m_Model->setFocusPolicy( QWidget::NoFocus );
	m_Model->setBackgroundMode( QWidget::PaletteBackground );
	m_Model->setFontPropagation( QWidget::NoChildren );
	m_Model->setPalettePropagation( QWidget::NoChildren );
	m_Model->setFrameStyle( 0 );
	m_Model->setLineWidth( 1 );
	m_Model->setMidLineWidth( 0 );
	m_Model->QFrame::setMargin( 0 );
	m_Model->setText( "---" );
	m_Model->setAlignment( 289 );
	m_Model->setMargin( -1 );

	m_MountedOn = new QLabel( this, "Label_21" );
	m_MountedOn->setGeometry( 102, 80, 375, 20 );
	m_MountedOn->setMinimumSize( 0, 0 );
	m_MountedOn->setMaximumSize( 32767, 32767 );
	m_MountedOn->setFocusPolicy( QWidget::NoFocus );
	m_MountedOn->setBackgroundMode( QWidget::PaletteBackground );
	m_MountedOn->setFontPropagation( QWidget::NoChildren );
	m_MountedOn->setPalettePropagation( QWidget::NoChildren );
	m_MountedOn->setFrameStyle( 0 );
	m_MountedOn->setLineWidth( 1 );
	m_MountedOn->setMidLineWidth( 0 );
	m_MountedOn->QFrame::setMargin( 0 );
	m_MountedOn->setText( "---" );
	m_MountedOn->setAlignment( 289 );
	m_MountedOn->setMargin( -1 );

	m_MountedOnLabel = new QLabel( this, "Label_22" );
	m_MountedOnLabel->setGeometry( 12, 80, 80, 20 );
	m_MountedOnLabel->setMinimumSize( 0, 0 );
	m_MountedOnLabel->setMaximumSize( 32767, 32767 );
	m_MountedOnLabel->setFocusPolicy( QWidget::NoFocus );
	m_MountedOnLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_MountedOnLabel->setFontPropagation( QWidget::NoChildren );
	m_MountedOnLabel->setPalettePropagation( QWidget::NoChildren );
	m_MountedOnLabel->setFrameStyle( 0 );
	m_MountedOnLabel->setLineWidth( 1 );
	m_MountedOnLabel->setMidLineWidth( 0 );
	m_MountedOnLabel->QFrame::setMargin( 0 );
	m_MountedOnLabel->setText( "Mounted on:" );
	m_MountedOnLabel->setAlignment( 289 );
	m_MountedOnLabel->setMargin( -1 );

	m_NotMountedLabel = new QLabel( this, "Label_23" );
	m_NotMountedLabel->setGeometry( 12, 80, 465, 20 );
	m_NotMountedLabel->setMinimumSize( 0, 0 );
	m_NotMountedLabel->setMaximumSize( 32767, 32767 );
	m_NotMountedLabel->setFocusPolicy( QWidget::NoFocus );
	m_NotMountedLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_NotMountedLabel->setFontPropagation( QWidget::NoChildren );
	m_NotMountedLabel->setPalettePropagation( QWidget::NoChildren );
	m_NotMountedLabel->setFrameStyle( 0 );
	m_NotMountedLabel->setLineWidth( 1 );
	m_NotMountedLabel->setMidLineWidth( 0 );
	m_NotMountedLabel->QFrame::setMargin( 0 );
	m_NotMountedLabel->setText( "---" );
	m_NotMountedLabel->setAlignment( 289 );
	m_NotMountedLabel->setMargin( -1 );

	resize( 489,350 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


CDevicePropGeneralData::~CDevicePropGeneralData()
{
}
