/* Name: DevicePropGeneralData.h

   Description: This file is a part of the Corel File Manager application.

   Author:	Oleg Noskov (olegn@corel.com)

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/

/*
 * NOTE: This source file was created using tab size = 2.
 * Please respect that setting in case of modifications.
 */

/**********************************************************************

	--- Qt Architect generated file ---

	File: DevicePropGeneralData.h
	Last generated: Tue Oct 19 12:34:41 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CDevicePropGeneralData_included
#define CDevicePropGeneralData_included

#include <qdialog.h>
#include <qlabel.h>

class CDevicePropGeneralData : public QDialog
{
    Q_OBJECT

public:

    CDevicePropGeneralData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CDevicePropGeneralData();

public slots:


protected slots:


protected:
    QLabel* m_IconLabel;
    QLabel* m_Name;
    QLabel* m_DeviceLabel;
    QLabel* m_Device;
    QLabel* m_DriverLabel;
    QLabel* m_Driver;
    QLabel* m_ModelLabel;
    QLabel* m_Model;
    QLabel* m_MountedOn;
    QLabel* m_MountedOnLabel;
    QLabel* m_NotMountedLabel;

};

#endif // CDevicePropGeneralData_included
