/* Name: FilePermissionsData.h

   Description: This file is a part of the Corel File Manager application.

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/

/**********************************************************************

	--- Qt Architect generated file ---

	File: FilePermissionsData.h
	Last generated: Wed May 10 13:30:46 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CFilePermissionsData_included
#define CFilePermissionsData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qcheckbox.h>
#include <qcombobox.h>
#include <qgroupbox.h>

class CFilePermissionsData : public QDialog
{
    Q_OBJECT

public:

    CFilePermissionsData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CFilePermissionsData();

public slots:


protected slots:


protected:
    QGroupBox* m_pOwnershipGroupBox;
    QGroupBox* m_pAccessPermissionsGroupBox;
    QLabel* m_pReadLabel;
    QLabel* m_pWriteLabel;
    QLabel* m_pExecLabel;
    QLabel* m_pSpecialLabel;
    QLabel* m_pUserLabel;
    QLabel* m_pGroupLabel;
    QLabel* m_pOthersLabel;
    QLabel* m_pSetUIDLabel;
    QLabel* m_pSetGIDLabel;
    QLabel* m_pStickyLabel;
    QCheckBox* m_IRUSR;
    QCheckBox* m_IWUSR;
    QCheckBox* m_IXUSR;
    QCheckBox* m_ISUID;
    QCheckBox* m_IRGRP;
    QCheckBox* m_IROTH;
    QCheckBox* m_IWGRP;
    QCheckBox* m_IXGRP;
    QCheckBox* m_IWOTH;
    QCheckBox* m_IXOTH;
    QCheckBox* m_ISGID;
    QCheckBox* m_ISVTX;
    QLabel* m_pOwnerLabel;
    QLabel* m_pGroupLabel2;
    QComboBox* m_Group;
    QComboBox* m_Owner;
    QLabel* m_pIconLabel;
    QLabel* m_Name;

};

#endif // CFilePermissionsData_included
