/* Name: FilePropGeneralData.cpp

   Description: This file is a part of the Corel File Manager application.

   Author:	Oleg Noskov (olegn@corel.com)

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/

/**********************************************************************

	--- Qt Architect generated file ---

	File: FilePropGeneralData.cpp
	Last generated: Wed May 10 13:25:00 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "FilePropGeneralData.h"

#define Inherited QDialog

#include <qframe.h>

CFilePropGeneralData::CFilePropGeneralData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	m_IconLabel = new QLabel( this, "Label_1" );
	m_IconLabel->setGeometry( 10, 10, 60, 40 );
	m_IconLabel->setMinimumSize( 0, 0 );
	m_IconLabel->setMaximumSize( 32767, 32767 );
	m_IconLabel->setFocusPolicy( QWidget::NoFocus );
	m_IconLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_IconLabel->setFontPropagation( QWidget::NoChildren );
	m_IconLabel->setPalettePropagation( QWidget::NoChildren );
	m_IconLabel->setFrameStyle( 0 );
	m_IconLabel->setLineWidth( 1 );
	m_IconLabel->setMidLineWidth( 0 );
	m_IconLabel->QFrame::setMargin( 0 );
	m_IconLabel->setText( "---" );
	m_IconLabel->setAlignment( 289 );
	m_IconLabel->setMargin( -1 );

	m_FileName = new QLabel( this, "Label_12" );
	m_FileName->setGeometry( 80, 10, 395, 52 );
	m_FileName->setMinimumSize( 0, 0 );
	m_FileName->setMaximumSize( 32767, 32767 );
	m_FileName->setFocusPolicy( QWidget::NoFocus );
	m_FileName->setBackgroundMode( QWidget::PaletteBackground );
	m_FileName->setFontPropagation( QWidget::NoChildren );
	m_FileName->setPalettePropagation( QWidget::NoChildren );
	m_FileName->setFrameStyle( 0 );
	m_FileName->setLineWidth( 1 );
	m_FileName->setMidLineWidth( 0 );
	m_FileName->QFrame::setMargin( 0 );
	m_FileName->setText( "---" );
	m_FileName->setAlignment( 289 );
	m_FileName->setMargin( -1 );

	QFrame* qtarch_Frame_4;
	qtarch_Frame_4 = new QFrame( this, "Frame_4" );
	qtarch_Frame_4->setGeometry( 12, 66, 464, 10 );
	qtarch_Frame_4->setMinimumSize( 0, 0 );
	qtarch_Frame_4->setMaximumSize( 32767, 32767 );
	qtarch_Frame_4->setFocusPolicy( QWidget::NoFocus );
	qtarch_Frame_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Frame_4->setFontPropagation( QWidget::NoChildren );
	qtarch_Frame_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_Frame_4->setFrameStyle( 52 );
	qtarch_Frame_4->setLineWidth( 1 );
	qtarch_Frame_4->setMidLineWidth( 0 );
	qtarch_Frame_4->QFrame::setMargin( 0 );

	m_FullNameLabel = new QLabel( this, "Label_13" );
	m_FullNameLabel->setGeometry( 12, 80, 135, 20 );
	m_FullNameLabel->setMinimumSize( 0, 0 );
	m_FullNameLabel->setMaximumSize( 32767, 32767 );
	m_FullNameLabel->setFocusPolicy( QWidget::NoFocus );
	m_FullNameLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_FullNameLabel->setFontPropagation( QWidget::NoChildren );
	m_FullNameLabel->setPalettePropagation( QWidget::NoChildren );
	m_FullNameLabel->setFrameStyle( 0 );
	m_FullNameLabel->setLineWidth( 1 );
	m_FullNameLabel->setMidLineWidth( 0 );
	m_FullNameLabel->QFrame::setMargin( 0 );
	m_FullNameLabel->setText( "---" );
	m_FullNameLabel->setAlignment( 289 );
	m_FullNameLabel->setMargin( -1 );

	m_FullName = new QLabel( this, "Label_15" );
	m_FullName->setGeometry( 150, 79, 327, 20 );
	m_FullName->setMinimumSize( 0, 0 );
	m_FullName->setMaximumSize( 32767, 32767 );
	m_FullName->setFocusPolicy( QWidget::NoFocus );
	m_FullName->setBackgroundMode( QWidget::PaletteBackground );
	m_FullName->setFontPropagation( QWidget::NoChildren );
	m_FullName->setPalettePropagation( QWidget::NoChildren );
	m_FullName->setFrameStyle( 0 );
	m_FullName->setLineWidth( 1 );
	m_FullName->setMidLineWidth( 0 );
	m_FullName->QFrame::setMargin( 0 );
	m_FullName->setText( "---" );
	m_FullName->setAlignment( 289 );
	m_FullName->setMargin( -1 );

	m_SizeLabel = new QLabel( this, "Label_16" );
	m_SizeLabel->setGeometry( 12, 108, 135, 18 );
	m_SizeLabel->setMinimumSize( 0, 0 );
	m_SizeLabel->setMaximumSize( 32767, 32767 );
	m_SizeLabel->setFocusPolicy( QWidget::NoFocus );
	m_SizeLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_SizeLabel->setFontPropagation( QWidget::NoChildren );
	m_SizeLabel->setPalettePropagation( QWidget::NoChildren );
	m_SizeLabel->setFrameStyle( 0 );
	m_SizeLabel->setLineWidth( 1 );
	m_SizeLabel->setMidLineWidth( 0 );
	m_SizeLabel->QFrame::setMargin( 0 );
	m_SizeLabel->setText( "---" );
	m_SizeLabel->setAlignment( 289 );
	m_SizeLabel->setMargin( -1 );

	m_Size = new QLabel( this, "Label_18" );
	m_Size->setGeometry( 150, 108, 327, 20 );
	m_Size->setMinimumSize( 0, 0 );
	m_Size->setMaximumSize( 32767, 32767 );
	m_Size->setFocusPolicy( QWidget::NoFocus );
	m_Size->setBackgroundMode( QWidget::PaletteBackground );
	m_Size->setFontPropagation( QWidget::NoChildren );
	m_Size->setPalettePropagation( QWidget::NoChildren );
	m_Size->setFrameStyle( 0 );
	m_Size->setLineWidth( 1 );
	m_Size->setMidLineWidth( 0 );
	m_Size->QFrame::setMargin( 0 );
	m_Size->setText( "---" );
	m_Size->setAlignment( 289 );
	m_Size->setMargin( -1 );

	m_CreatedLabel = new QLabel( this, "Label_19" );
	m_CreatedLabel->setGeometry( 12, 137, 135, 20 );
	m_CreatedLabel->setMinimumSize( 0, 0 );
	m_CreatedLabel->setMaximumSize( 32767, 32767 );
	m_CreatedLabel->setFocusPolicy( QWidget::NoFocus );
	m_CreatedLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_CreatedLabel->setFontPropagation( QWidget::NoChildren );
	m_CreatedLabel->setPalettePropagation( QWidget::NoChildren );
	m_CreatedLabel->setFrameStyle( 0 );
	m_CreatedLabel->setLineWidth( 1 );
	m_CreatedLabel->setMidLineWidth( 0 );
	m_CreatedLabel->QFrame::setMargin( 0 );
	m_CreatedLabel->setText( "---" );
	m_CreatedLabel->setAlignment( 289 );
	m_CreatedLabel->setMargin( -1 );

	m_CreateDate = new QLabel( this, "Label_20" );
	m_CreateDate->setGeometry( 150, 137, 327, 20 );
	m_CreateDate->setMinimumSize( 0, 0 );
	m_CreateDate->setMaximumSize( 32767, 32767 );
	m_CreateDate->setFocusPolicy( QWidget::NoFocus );
	m_CreateDate->setBackgroundMode( QWidget::PaletteBackground );
	m_CreateDate->setFontPropagation( QWidget::NoChildren );
	m_CreateDate->setPalettePropagation( QWidget::NoChildren );
	m_CreateDate->setFrameStyle( 0 );
	m_CreateDate->setLineWidth( 1 );
	m_CreateDate->setMidLineWidth( 0 );
	m_CreateDate->QFrame::setMargin( 0 );
	m_CreateDate->setText( "---" );
	m_CreateDate->setAlignment( 289 );
	m_CreateDate->setMargin( -1 );

	m_ModifiedLabel = new QLabel( this, "Label_21" );
	m_ModifiedLabel->setGeometry( 12, 166, 135, 20 );
	m_ModifiedLabel->setMinimumSize( 0, 0 );
	m_ModifiedLabel->setMaximumSize( 32767, 32767 );
	m_ModifiedLabel->setFocusPolicy( QWidget::NoFocus );
	m_ModifiedLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_ModifiedLabel->setFontPropagation( QWidget::NoChildren );
	m_ModifiedLabel->setPalettePropagation( QWidget::NoChildren );
	m_ModifiedLabel->setFrameStyle( 0 );
	m_ModifiedLabel->setLineWidth( 1 );
	m_ModifiedLabel->setMidLineWidth( 0 );
	m_ModifiedLabel->QFrame::setMargin( 0 );
	m_ModifiedLabel->setText( "---" );
	m_ModifiedLabel->setAlignment( 289 );
	m_ModifiedLabel->setMargin( -1 );

	m_ModifyDate = new QLabel( this, "Label_22" );
	m_ModifyDate->setGeometry( 150, 166, 327, 20 );
	m_ModifyDate->setMinimumSize( 0, 0 );
	m_ModifyDate->setMaximumSize( 32767, 32767 );
	m_ModifyDate->setFocusPolicy( QWidget::NoFocus );
	m_ModifyDate->setBackgroundMode( QWidget::PaletteBackground );
	m_ModifyDate->setFontPropagation( QWidget::NoChildren );
	m_ModifyDate->setPalettePropagation( QWidget::NoChildren );
	m_ModifyDate->setFrameStyle( 0 );
	m_ModifyDate->setLineWidth( 1 );
	m_ModifyDate->setMidLineWidth( 0 );
	m_ModifyDate->QFrame::setMargin( 0 );
	m_ModifyDate->setText( "---" );
	m_ModifyDate->setAlignment( 289 );
	m_ModifyDate->setMargin( -1 );

	m_AccessedLabel = new QLabel( this, "Label_23" );
	m_AccessedLabel->setGeometry( 11, 195, 135, 20 );
	m_AccessedLabel->setMinimumSize( 0, 0 );
	m_AccessedLabel->setMaximumSize( 32767, 32767 );
	m_AccessedLabel->setFocusPolicy( QWidget::NoFocus );
	m_AccessedLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_AccessedLabel->setFontPropagation( QWidget::NoChildren );
	m_AccessedLabel->setPalettePropagation( QWidget::NoChildren );
	m_AccessedLabel->setFrameStyle( 0 );
	m_AccessedLabel->setLineWidth( 1 );
	m_AccessedLabel->setMidLineWidth( 0 );
	m_AccessedLabel->QFrame::setMargin( 0 );
	m_AccessedLabel->setText( "---" );
	m_AccessedLabel->setAlignment( 289 );
	m_AccessedLabel->setMargin( -1 );

	m_AccessDate = new QLabel( this, "Label_24" );
	m_AccessDate->setGeometry( 150, 195, 327, 20 );
	m_AccessDate->setMinimumSize( 0, 0 );
	m_AccessDate->setMaximumSize( 32767, 32767 );
	m_AccessDate->setFocusPolicy( QWidget::NoFocus );
	m_AccessDate->setBackgroundMode( QWidget::PaletteBackground );
	m_AccessDate->setFontPropagation( QWidget::NoChildren );
	m_AccessDate->setPalettePropagation( QWidget::NoChildren );
	m_AccessDate->setFrameStyle( 0 );
	m_AccessDate->setLineWidth( 1 );
	m_AccessDate->setMidLineWidth( 0 );
	m_AccessDate->QFrame::setMargin( 0 );
	m_AccessDate->setText( "---" );
	m_AccessDate->setAlignment( 289 );
	m_AccessDate->setMargin( -1 );

	m_OwnerLabel = new QLabel( this, "Label_25" );
	m_OwnerLabel->setGeometry( 12, 234, 135, 20 );
	m_OwnerLabel->setMinimumSize( 0, 0 );
	m_OwnerLabel->setMaximumSize( 32767, 32767 );
	m_OwnerLabel->setFocusPolicy( QWidget::NoFocus );
	m_OwnerLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_OwnerLabel->setFontPropagation( QWidget::NoChildren );
	m_OwnerLabel->setPalettePropagation( QWidget::NoChildren );
	m_OwnerLabel->setFrameStyle( 0 );
	m_OwnerLabel->setLineWidth( 1 );
	m_OwnerLabel->setMidLineWidth( 0 );
	m_OwnerLabel->QFrame::setMargin( 0 );
	m_OwnerLabel->setText( "---" );
	m_OwnerLabel->setAlignment( 289 );
	m_OwnerLabel->setMargin( -1 );

	QFrame* qtarch_Frame_5;
	qtarch_Frame_5 = new QFrame( this, "Frame_5" );
	qtarch_Frame_5->setGeometry( 12, 220, 464, 10 );
	qtarch_Frame_5->setMinimumSize( 0, 0 );
	qtarch_Frame_5->setMaximumSize( 32767, 32767 );
	qtarch_Frame_5->setFocusPolicy( QWidget::NoFocus );
	qtarch_Frame_5->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Frame_5->setFontPropagation( QWidget::NoChildren );
	qtarch_Frame_5->setPalettePropagation( QWidget::NoChildren );
	qtarch_Frame_5->setFrameStyle( 52 );
	qtarch_Frame_5->setLineWidth( 1 );
	qtarch_Frame_5->setMidLineWidth( 0 );
	qtarch_Frame_5->QFrame::setMargin( 0 );

	m_Owner = new QLabel( this, "Label_26" );
	m_Owner->setGeometry( 150, 234, 327, 20 );
	m_Owner->setMinimumSize( 0, 0 );
	m_Owner->setMaximumSize( 32767, 32767 );
	m_Owner->setFocusPolicy( QWidget::NoFocus );
	m_Owner->setBackgroundMode( QWidget::PaletteBackground );
	m_Owner->setFontPropagation( QWidget::NoChildren );
	m_Owner->setPalettePropagation( QWidget::NoChildren );
	m_Owner->setFrameStyle( 0 );
	m_Owner->setLineWidth( 1 );
	m_Owner->setMidLineWidth( 0 );
	m_Owner->QFrame::setMargin( 0 );
	m_Owner->setText( "---" );
	m_Owner->setAlignment( 289 );
	m_Owner->setMargin( -1 );

	m_OwnerGroupLabel = new QLabel( this, "Label_27" );
	m_OwnerGroupLabel->setGeometry( 12, 263, 135, 20 );
	m_OwnerGroupLabel->setMinimumSize( 0, 0 );
	m_OwnerGroupLabel->setMaximumSize( 32767, 32767 );
	m_OwnerGroupLabel->setFocusPolicy( QWidget::NoFocus );
	m_OwnerGroupLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_OwnerGroupLabel->setFontPropagation( QWidget::NoChildren );
	m_OwnerGroupLabel->setPalettePropagation( QWidget::NoChildren );
	m_OwnerGroupLabel->setFrameStyle( 0 );
	m_OwnerGroupLabel->setLineWidth( 1 );
	m_OwnerGroupLabel->setMidLineWidth( 0 );
	m_OwnerGroupLabel->QFrame::setMargin( 0 );
	m_OwnerGroupLabel->setText( "---" );
	m_OwnerGroupLabel->setAlignment( 289 );
	m_OwnerGroupLabel->setMargin( -1 );

	m_OwnerGroup = new QLabel( this, "Label_28" );
	m_OwnerGroup->setGeometry( 150, 263, 327, 20 );
	m_OwnerGroup->setMinimumSize( 0, 0 );
	m_OwnerGroup->setMaximumSize( 32767, 32767 );
	m_OwnerGroup->setFocusPolicy( QWidget::NoFocus );
	m_OwnerGroup->setBackgroundMode( QWidget::PaletteBackground );
	m_OwnerGroup->setFontPropagation( QWidget::NoChildren );
	m_OwnerGroup->setPalettePropagation( QWidget::NoChildren );
	m_OwnerGroup->setFrameStyle( 0 );
	m_OwnerGroup->setLineWidth( 1 );
	m_OwnerGroup->setMidLineWidth( 0 );
	m_OwnerGroup->QFrame::setMargin( 0 );
	m_OwnerGroup->setText( "---" );
	m_OwnerGroup->setAlignment( 289 );
	m_OwnerGroup->setMargin( -1 );

	m_PermissionsLabel = new QLabel( this, "Label_29" );
	m_PermissionsLabel->setGeometry( 12, 292, 135, 20 );
	m_PermissionsLabel->setMinimumSize( 0, 0 );
	m_PermissionsLabel->setMaximumSize( 32767, 32767 );
	m_PermissionsLabel->setFocusPolicy( QWidget::NoFocus );
	m_PermissionsLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_PermissionsLabel->setFontPropagation( QWidget::NoChildren );
	m_PermissionsLabel->setPalettePropagation( QWidget::NoChildren );
	m_PermissionsLabel->setFrameStyle( 0 );
	m_PermissionsLabel->setLineWidth( 1 );
	m_PermissionsLabel->setMidLineWidth( 0 );
	m_PermissionsLabel->QFrame::setMargin( 0 );
	m_PermissionsLabel->setText( "---" );
	m_PermissionsLabel->setAlignment( 289 );
	m_PermissionsLabel->setMargin( -1 );

	m_Permissions = new QLabel( this, "Label_30" );
	m_Permissions->setGeometry( 150, 292, 327, 20 );
	m_Permissions->setMinimumSize( 0, 0 );
	m_Permissions->setMaximumSize( 32767, 32767 );
	m_Permissions->setFocusPolicy( QWidget::NoFocus );
	m_Permissions->setBackgroundMode( QWidget::PaletteBackground );
	m_Permissions->setFontPropagation( QWidget::NoChildren );
	m_Permissions->setPalettePropagation( QWidget::NoChildren );
	m_Permissions->setFrameStyle( 0 );
	m_Permissions->setLineWidth( 1 );
	m_Permissions->setMidLineWidth( 0 );
	m_Permissions->QFrame::setMargin( 0 );
	m_Permissions->setText( "---" );
	m_Permissions->setAlignment( 289 );
	m_Permissions->setMargin( -1 );

	resize( 489,350 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


CFilePropGeneralData::~CFilePropGeneralData()
{
}
