/* Name: FilePropGeneralData.h

   Description: This file is a part of the Corel File Manager application.

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/

/**********************************************************************

	--- Qt Architect generated file ---

	File: FilePropGeneralData.h
	Last generated: Wed May 10 13:25:00 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CFilePropGeneralData_included
#define CFilePropGeneralData_included

#include <qdialog.h>
#include <qlabel.h>

class CFilePropGeneralData : public QDialog
{
    Q_OBJECT

public:

    CFilePropGeneralData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CFilePropGeneralData();

public slots:


protected slots:


protected:
    QLabel* m_IconLabel;
    QLabel* m_FileName;
    QLabel* m_FullNameLabel;
    QLabel* m_FullName;
    QLabel* m_SizeLabel;
    QLabel* m_Size;
    QLabel* m_CreatedLabel;
    QLabel* m_CreateDate;
    QLabel* m_ModifiedLabel;
    QLabel* m_ModifyDate;
    QLabel* m_AccessedLabel;
    QLabel* m_AccessDate;
    QLabel* m_OwnerLabel;
    QLabel* m_Owner;
    QLabel* m_OwnerGroupLabel;
    QLabel* m_OwnerGroup;
    QLabel* m_PermissionsLabel;
    QLabel* m_Permissions;

};

#endif // CFilePropGeneralData_included
