/* Name: FSPropGeneralData.cpp

   Description: This file is a part of the Corel File Manager application.

   Author:	Oleg Noskov (olegn@corel.com)

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/

/*
 * NOTE: This source file was created using tab size = 2.
 * Please respect that setting in case of modifications.
 */


/**********************************************************************

	--- Qt Architect generated file ---

	File: FSPropGeneralData.cpp
	Last generated: Wed Oct 20 08:29:10 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "FSPropGeneralData.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qframe.h>

CFSPropGeneralData::CFSPropGeneralData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	m_IconLabel = new QLabel( this, "Label_1" );
	m_IconLabel->setGeometry( 10, 10, 60, 40 );
	m_IconLabel->setMinimumSize( 0, 0 );
	m_IconLabel->setMaximumSize( 32767, 32767 );
	m_IconLabel->setFocusPolicy( QWidget::NoFocus );
	m_IconLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_IconLabel->setFontPropagation( QWidget::NoChildren );
	m_IconLabel->setPalettePropagation( QWidget::NoChildren );
	m_IconLabel->setFrameStyle( 0 );
	m_IconLabel->setLineWidth( 1 );
	m_IconLabel->setMidLineWidth( 0 );
	m_IconLabel->QFrame::setMargin( 0 );
	m_IconLabel->setText( "---" );
	m_IconLabel->setAlignment( 289 );
	m_IconLabel->setMargin( -1 );

	m_TypeLabel = new QLabel( this, "Label_3" );
	m_TypeLabel->setGeometry( 75, 15, 170, 20 );
	m_TypeLabel->setMinimumSize( 0, 0 );
	m_TypeLabel->setMaximumSize( 32767, 32767 );
	m_TypeLabel->setFocusPolicy( QWidget::NoFocus );
	m_TypeLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_TypeLabel->setFontPropagation( QWidget::NoChildren );
	m_TypeLabel->setPalettePropagation( QWidget::NoChildren );
	m_TypeLabel->setFrameStyle( 0 );
	m_TypeLabel->setLineWidth( 1 );
	m_TypeLabel->setMidLineWidth( 0 );
	m_TypeLabel->QFrame::setMargin( 0 );
	m_TypeLabel->setText( "---" );
	m_TypeLabel->setAlignment( 289 );
	m_TypeLabel->setMargin( -1 );

	m_Type = new QLabel( this, "Label_4" );
	m_Type->setGeometry( 250, 15, 224, 20 );
	m_Type->setMinimumSize( 0, 0 );
	m_Type->setMaximumSize( 32767, 32767 );
	m_Type->setFocusPolicy( QWidget::NoFocus );
	m_Type->setBackgroundMode( QWidget::PaletteBackground );
	m_Type->setFontPropagation( QWidget::NoChildren );
	m_Type->setPalettePropagation( QWidget::NoChildren );
	m_Type->setFrameStyle( 0 );
	m_Type->setLineWidth( 1 );
	m_Type->setMidLineWidth( 0 );
	m_Type->QFrame::setMargin( 0 );
	m_Type->setText( "---" );
	m_Type->setAlignment( 289 );
	m_Type->setMargin( -1 );

	m_UsedSpaceLabel = new QLabel( this, "Label_5" );
	m_UsedSpaceLabel->setGeometry( 75, 142, 135, 20 );
	m_UsedSpaceLabel->setMinimumSize( 0, 0 );
	m_UsedSpaceLabel->setMaximumSize( 32767, 32767 );
	m_UsedSpaceLabel->setFocusPolicy( QWidget::NoFocus );
	m_UsedSpaceLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_UsedSpaceLabel->setFontPropagation( QWidget::NoChildren );
	m_UsedSpaceLabel->setPalettePropagation( QWidget::NoChildren );
	m_UsedSpaceLabel->setFrameStyle( 0 );
	m_UsedSpaceLabel->setLineWidth( 1 );
	m_UsedSpaceLabel->setMidLineWidth( 0 );
	m_UsedSpaceLabel->QFrame::setMargin( 0 );
	m_UsedSpaceLabel->setText( "---" );
	m_UsedSpaceLabel->setAlignment( 289 );
	m_UsedSpaceLabel->setMargin( -1 );

	m_FreeSpaceLabel = new QLabel( this, "Label_6" );
	m_FreeSpaceLabel->setGeometry( 75, 170, 135, 20 );
	m_FreeSpaceLabel->setMinimumSize( 0, 0 );
	m_FreeSpaceLabel->setMaximumSize( 32767, 32767 );
	m_FreeSpaceLabel->setFocusPolicy( QWidget::NoFocus );
	m_FreeSpaceLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_FreeSpaceLabel->setFontPropagation( QWidget::NoChildren );
	m_FreeSpaceLabel->setPalettePropagation( QWidget::NoChildren );
	m_FreeSpaceLabel->setFrameStyle( 0 );
	m_FreeSpaceLabel->setLineWidth( 1 );
	m_FreeSpaceLabel->setMidLineWidth( 0 );
	m_FreeSpaceLabel->QFrame::setMargin( 0 );
	m_FreeSpaceLabel->setText( "---" );
	m_FreeSpaceLabel->setAlignment( 289 );
	m_FreeSpaceLabel->setMargin( -1 );

	QFrame* qtarch_Frame_3;
	qtarch_Frame_3 = new QFrame( this, "Frame_3" );
	qtarch_Frame_3->setGeometry( 75, 90, 410, 13 );
	qtarch_Frame_3->setMinimumSize( 0, 0 );
	qtarch_Frame_3->setMaximumSize( 32767, 32767 );
	qtarch_Frame_3->setFocusPolicy( QWidget::NoFocus );
	qtarch_Frame_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Frame_3->setFontPropagation( QWidget::NoChildren );
	qtarch_Frame_3->setPalettePropagation( QWidget::NoChildren );
	qtarch_Frame_3->setFrameStyle( 52 );
	qtarch_Frame_3->setLineWidth( 1 );
	qtarch_Frame_3->setMidLineWidth( 0 );
	qtarch_Frame_3->QFrame::setMargin( 0 );

	m_CapacityLabel = new QLabel( this, "Label_7" );
	m_CapacityLabel->setGeometry( 75, 112, 135, 20 );
	m_CapacityLabel->setMinimumSize( 0, 0 );
	m_CapacityLabel->setMaximumSize( 32767, 32767 );
	m_CapacityLabel->setFocusPolicy( QWidget::NoFocus );
	m_CapacityLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_CapacityLabel->setFontPropagation( QWidget::NoChildren );
	m_CapacityLabel->setPalettePropagation( QWidget::NoChildren );
	m_CapacityLabel->setFrameStyle( 0 );
	m_CapacityLabel->setLineWidth( 1 );
	m_CapacityLabel->setMidLineWidth( 0 );
	m_CapacityLabel->QFrame::setMargin( 0 );
	m_CapacityLabel->setText( "---" );
	m_CapacityLabel->setAlignment( 289 );
	m_CapacityLabel->setMargin( -1 );

	m_FileSystemTypeLabel = new QLabel( this, "Label_8" );
	m_FileSystemTypeLabel->setGeometry( 75, 40, 170, 20 );
	m_FileSystemTypeLabel->setMinimumSize( 0, 0 );
	m_FileSystemTypeLabel->setMaximumSize( 32767, 32767 );
	m_FileSystemTypeLabel->setFocusPolicy( QWidget::NoFocus );
	m_FileSystemTypeLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_FileSystemTypeLabel->setFontPropagation( QWidget::NoChildren );
	m_FileSystemTypeLabel->setPalettePropagation( QWidget::NoChildren );
	m_FileSystemTypeLabel->setFrameStyle( 0 );
	m_FileSystemTypeLabel->setLineWidth( 1 );
	m_FileSystemTypeLabel->setMidLineWidth( 0 );
	m_FileSystemTypeLabel->QFrame::setMargin( 0 );
	m_FileSystemTypeLabel->setText( "---" );
	m_FileSystemTypeLabel->setAlignment( 289 );
	m_FileSystemTypeLabel->setMargin( -1 );

	m_FileSystemType = new QLabel( this, "Label_9" );
	m_FileSystemType->setGeometry( 250, 39, 224, 20 );
	m_FileSystemType->setMinimumSize( 0, 0 );
	m_FileSystemType->setMaximumSize( 32767, 32767 );
	m_FileSystemType->setFocusPolicy( QWidget::NoFocus );
	m_FileSystemType->setBackgroundMode( QWidget::PaletteBackground );
	m_FileSystemType->setFontPropagation( QWidget::NoChildren );
	m_FileSystemType->setPalettePropagation( QWidget::NoChildren );
	m_FileSystemType->setFrameStyle( 0 );
	m_FileSystemType->setLineWidth( 1 );
	m_FileSystemType->setMidLineWidth( 0 );
	m_FileSystemType->QFrame::setMargin( 0 );
	m_FileSystemType->setText( "---" );
	m_FileSystemType->setAlignment( 289 );
	m_FileSystemType->setMargin( -1 );

	m_MountedFromLabel = new QLabel( this, "Label_10" );
	m_MountedFromLabel->setGeometry( 75, 65, 170, 20 );
	m_MountedFromLabel->setMinimumSize( 0, 0 );
	m_MountedFromLabel->setMaximumSize( 32767, 32767 );
	m_MountedFromLabel->setFocusPolicy( QWidget::NoFocus );
	m_MountedFromLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_MountedFromLabel->setFontPropagation( QWidget::NoChildren );
	m_MountedFromLabel->setPalettePropagation( QWidget::NoChildren );
	m_MountedFromLabel->setFrameStyle( 0 );
	m_MountedFromLabel->setLineWidth( 1 );
	m_MountedFromLabel->setMidLineWidth( 0 );
	m_MountedFromLabel->QFrame::setMargin( 0 );
	m_MountedFromLabel->setText( "---" );
	m_MountedFromLabel->setAlignment( 289 );
	m_MountedFromLabel->setMargin( -1 );

	m_FileSystemPath = new QLabel( this, "Label_11" );
	m_FileSystemPath->setGeometry( 250, 65, 224, 20 );
	m_FileSystemPath->setMinimumSize( 0, 0 );
	m_FileSystemPath->setMaximumSize( 32767, 32767 );
	m_FileSystemPath->setFocusPolicy( QWidget::NoFocus );
	m_FileSystemPath->setBackgroundMode( QWidget::PaletteBackground );
	m_FileSystemPath->setFontPropagation( QWidget::NoChildren );
	m_FileSystemPath->setPalettePropagation( QWidget::NoChildren );
	m_FileSystemPath->setFrameStyle( 0 );
	m_FileSystemPath->setLineWidth( 1 );
	m_FileSystemPath->setMidLineWidth( 0 );
	m_FileSystemPath->QFrame::setMargin( 0 );
	m_FileSystemPath->setText( "---" );
	m_FileSystemPath->setAlignment( 289 );
	m_FileSystemPath->setMargin( -1 );

	m_Bar = new QProgressBar( 100, this, "ProgressBar_1" );
	m_Bar->setGeometry( 73, 243, 249, 25 );
	m_Bar->setMinimumSize( 0, 0 );
	m_Bar->setMaximumSize( 32767, 32767 );
	m_Bar->setFocusPolicy( QWidget::NoFocus );
	m_Bar->setBackgroundMode( QWidget::PaletteBackground );
	m_Bar->setFontPropagation( QWidget::NoChildren );
	m_Bar->setPalettePropagation( QWidget::NoChildren );
	m_Bar->setFrameStyle( 51 );
	m_Bar->setLineWidth( 2 );
	m_Bar->setMidLineWidth( 0 );
	m_Bar->QFrame::setMargin( 0 );
	m_Bar->setProgress( -1 );

	QFrame* qtarch_Frame_9;
	qtarch_Frame_9 = new QFrame( this, "Frame_9" );
	qtarch_Frame_9->setGeometry( 75, 199, 410, 13 );
	qtarch_Frame_9->setMinimumSize( 0, 0 );
	qtarch_Frame_9->setMaximumSize( 32767, 32767 );
	qtarch_Frame_9->setFocusPolicy( QWidget::NoFocus );
	qtarch_Frame_9->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Frame_9->setFontPropagation( QWidget::NoChildren );
	qtarch_Frame_9->setPalettePropagation( QWidget::NoChildren );
	qtarch_Frame_9->setFrameStyle( 52 );
	qtarch_Frame_9->setLineWidth( 1 );
	qtarch_Frame_9->setMidLineWidth( 0 );
	qtarch_Frame_9->QFrame::setMargin( 0 );

	m_StatusLabel = new QLabel( this, "Label_34" );
	m_StatusLabel->setGeometry( 75, 222, 145, 13 );
	m_StatusLabel->setMinimumSize( 0, 0 );
	m_StatusLabel->setMaximumSize( 32767, 32767 );
	m_StatusLabel->setFocusPolicy( QWidget::NoFocus );
	m_StatusLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_StatusLabel->setFontPropagation( QWidget::NoChildren );
	m_StatusLabel->setPalettePropagation( QWidget::NoChildren );
	m_StatusLabel->setFrameStyle( 0 );
	m_StatusLabel->setLineWidth( 1 );
	m_StatusLabel->setMidLineWidth( 0 );
	m_StatusLabel->QFrame::setMargin( 0 );
	m_StatusLabel->setText( "---" );
	m_StatusLabel->setAlignment( 289 );
	m_StatusLabel->setMargin( -1 );

	QLabel* qtarch_Label_35;
	qtarch_Label_35 = new QLabel( this, "Label_35" );
	qtarch_Label_35->setGeometry( 75, 278, 11, 14 );
	qtarch_Label_35->setMinimumSize( 0, 0 );
	qtarch_Label_35->setMaximumSize( 32767, 32767 );
	qtarch_Label_35->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_35->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_35->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_35->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_35->setFrameStyle( 0 );
	qtarch_Label_35->setLineWidth( 1 );
	qtarch_Label_35->setMidLineWidth( 0 );
	qtarch_Label_35->QFrame::setMargin( 0 );
	qtarch_Label_35->setText( "E" );
	qtarch_Label_35->setAlignment( 289 );
	qtarch_Label_35->setMargin( -1 );

	QLabel* qtarch_Label_36;
	qtarch_Label_36 = new QLabel( this, "Label_36" );
	qtarch_Label_36->setGeometry( 76, 270, 8, 8 );
	qtarch_Label_36->setMinimumSize( 0, 0 );
	qtarch_Label_36->setMaximumSize( 32767, 32767 );
	qtarch_Label_36->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_36->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_36->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_36->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_36->setFrameStyle( 0 );
	qtarch_Label_36->setLineWidth( 1 );
	qtarch_Label_36->setMidLineWidth( 0 );
	qtarch_Label_36->QFrame::setMargin( 0 );
	qtarch_Label_36->setText( "|" );
	qtarch_Label_36->setAlignment( 289 );
	qtarch_Label_36->setMargin( -1 );

	QLabel* qtarch_Label_37;
	qtarch_Label_37 = new QLabel( this, "Label_37" );
	qtarch_Label_37->setGeometry( 202, 270, 8, 8 );
	qtarch_Label_37->setMinimumSize( 0, 0 );
	qtarch_Label_37->setMaximumSize( 32767, 32767 );
	qtarch_Label_37->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_37->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_37->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_37->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_37->setFrameStyle( 0 );
	qtarch_Label_37->setLineWidth( 1 );
	qtarch_Label_37->setMidLineWidth( 0 );
	qtarch_Label_37->QFrame::setMargin( 0 );
	qtarch_Label_37->setText( "|" );
	qtarch_Label_37->setAlignment( 289 );
	qtarch_Label_37->setMargin( -1 );

	m_BarEndLabel = new QLabel( this, "Label_38" );
	m_BarEndLabel->setGeometry( 320, 270, 8, 8 );
	m_BarEndLabel->setMinimumSize( 0, 0 );
	m_BarEndLabel->setMaximumSize( 32767, 32767 );
	m_BarEndLabel->setFocusPolicy( QWidget::NoFocus );
	m_BarEndLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_BarEndLabel->setFontPropagation( QWidget::NoChildren );
	m_BarEndLabel->setPalettePropagation( QWidget::NoChildren );
	m_BarEndLabel->setFrameStyle( 0 );
	m_BarEndLabel->setLineWidth( 1 );
	m_BarEndLabel->setMidLineWidth( 0 );
	m_BarEndLabel->QFrame::setMargin( 0 );
	m_BarEndLabel->setText( "|" );
	m_BarEndLabel->setAlignment( 289 );
	m_BarEndLabel->setMargin( -1 );

	QLabel* qtarch_Label_39;
	qtarch_Label_39 = new QLabel( this, "Label_39" );
	qtarch_Label_39->setGeometry( 319, 278, 11, 14 );
	qtarch_Label_39->setMinimumSize( 0, 0 );
	qtarch_Label_39->setMaximumSize( 32767, 32767 );
	qtarch_Label_39->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_39->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_39->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_39->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_39->setFrameStyle( 0 );
	qtarch_Label_39->setLineWidth( 1 );
	qtarch_Label_39->setMidLineWidth( 0 );
	qtarch_Label_39->QFrame::setMargin( 0 );
	qtarch_Label_39->setText( "F" );
	qtarch_Label_39->setAlignment( 289 );
	qtarch_Label_39->setMargin( -1 );

	m_Capacity1 = new QLabel( this, "Label_40" );
	m_Capacity1->setGeometry( 220, 112, 100, 20 );
	m_Capacity1->setMinimumSize( 0, 0 );
	m_Capacity1->setMaximumSize( 32767, 32767 );
	m_Capacity1->setFocusPolicy( QWidget::NoFocus );
	m_Capacity1->setBackgroundMode( QWidget::PaletteBackground );
	m_Capacity1->setFontPropagation( QWidget::NoChildren );
	m_Capacity1->setPalettePropagation( QWidget::NoChildren );
	m_Capacity1->setFrameStyle( 0 );
	m_Capacity1->setLineWidth( 1 );
	m_Capacity1->setMidLineWidth( 0 );
	m_Capacity1->QFrame::setMargin( 0 );
	m_Capacity1->setText( "---" );
	m_Capacity1->setAlignment( 290 );
	m_Capacity1->setMargin( -1 );

	m_UsedSpace1 = new QLabel( this, "Label_41" );
	m_UsedSpace1->setGeometry( 220, 142, 100, 20 );
	m_UsedSpace1->setMinimumSize( 0, 0 );
	m_UsedSpace1->setMaximumSize( 32767, 32767 );
	m_UsedSpace1->setFocusPolicy( QWidget::NoFocus );
	m_UsedSpace1->setBackgroundMode( QWidget::PaletteBackground );
	m_UsedSpace1->setFontPropagation( QWidget::NoChildren );
	m_UsedSpace1->setPalettePropagation( QWidget::NoChildren );
	m_UsedSpace1->setFrameStyle( 0 );
	m_UsedSpace1->setLineWidth( 1 );
	m_UsedSpace1->setMidLineWidth( 0 );
	m_UsedSpace1->QFrame::setMargin( 0 );
	m_UsedSpace1->setText( "---" );
	m_UsedSpace1->setAlignment( 290 );
	m_UsedSpace1->setMargin( -1 );

	m_FreeSpace1 = new QLabel( this, "Label_42" );
	m_FreeSpace1->setGeometry( 220, 170, 100, 20 );
	m_FreeSpace1->setMinimumSize( 0, 0 );
	m_FreeSpace1->setMaximumSize( 32767, 32767 );
	m_FreeSpace1->setFocusPolicy( QWidget::NoFocus );
	m_FreeSpace1->setBackgroundMode( QWidget::PaletteBackground );
	m_FreeSpace1->setFontPropagation( QWidget::NoChildren );
	m_FreeSpace1->setPalettePropagation( QWidget::NoChildren );
	m_FreeSpace1->setFrameStyle( 0 );
	m_FreeSpace1->setLineWidth( 1 );
	m_FreeSpace1->setMidLineWidth( 0 );
	m_FreeSpace1->QFrame::setMargin( 0 );
	m_FreeSpace1->setText( "---" );
	m_FreeSpace1->setAlignment( 290 );
	m_FreeSpace1->setMargin( -1 );

	m_Capacity2 = new QLabel( this, "Label_43" );
	m_Capacity2->setGeometry( 326, 112, 160, 20 );
	m_Capacity2->setMinimumSize( 0, 0 );
	m_Capacity2->setMaximumSize( 32767, 32767 );
	m_Capacity2->setFocusPolicy( QWidget::NoFocus );
	m_Capacity2->setBackgroundMode( QWidget::PaletteBackground );
	m_Capacity2->setFontPropagation( QWidget::NoChildren );
	m_Capacity2->setPalettePropagation( QWidget::NoChildren );
	m_Capacity2->setFrameStyle( 0 );
	m_Capacity2->setLineWidth( 1 );
	m_Capacity2->setMidLineWidth( 0 );
	m_Capacity2->QFrame::setMargin( 0 );
	m_Capacity2->setText( "---" );
	m_Capacity2->setAlignment( 290 );
	m_Capacity2->setMargin( -1 );

	m_UsedSpace2 = new QLabel( this, "Label_44" );
	m_UsedSpace2->setGeometry( 326, 143, 160, 20 );
	m_UsedSpace2->setMinimumSize( 0, 0 );
	m_UsedSpace2->setMaximumSize( 32767, 32767 );
	m_UsedSpace2->setFocusPolicy( QWidget::NoFocus );
	m_UsedSpace2->setBackgroundMode( QWidget::PaletteBackground );
	m_UsedSpace2->setFontPropagation( QWidget::NoChildren );
	m_UsedSpace2->setPalettePropagation( QWidget::NoChildren );
	m_UsedSpace2->setFrameStyle( 0 );
	m_UsedSpace2->setLineWidth( 1 );
	m_UsedSpace2->setMidLineWidth( 0 );
	m_UsedSpace2->QFrame::setMargin( 0 );
	m_UsedSpace2->setText( "---" );
	m_UsedSpace2->setAlignment( 290 );
	m_UsedSpace2->setMargin( -1 );

	m_FreeSpace2 = new QLabel( this, "Label_45" );
	m_FreeSpace2->setGeometry( 326, 170, 160, 20 );
	m_FreeSpace2->setMinimumSize( 0, 0 );
	m_FreeSpace2->setMaximumSize( 32767, 32767 );
	m_FreeSpace2->setFocusPolicy( QWidget::NoFocus );
	m_FreeSpace2->setBackgroundMode( QWidget::PaletteBackground );
	m_FreeSpace2->setFontPropagation( QWidget::NoChildren );
	m_FreeSpace2->setPalettePropagation( QWidget::NoChildren );
	m_FreeSpace2->setFrameStyle( 0 );
	m_FreeSpace2->setLineWidth( 1 );
	m_FreeSpace2->setMidLineWidth( 0 );
	m_FreeSpace2->QFrame::setMargin( 0 );
	m_FreeSpace2->setText( "---" );
	m_FreeSpace2->setAlignment( 290 );
	m_FreeSpace2->setMargin( -1 );

	resize( 502,350 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


CFSPropGeneralData::~CFSPropGeneralData()
{
}
