/* Name: FSPropPropGeneralData.h

   Description: This file is a part of the Corel File Manager application.

   Author:	Oleg Noskov (olegn@corel.com)

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/

/*
 * NOTE: This source file was created using tab size = 2.
 * Please respect that setting in case of modifications.
 */

/**********************************************************************

	--- Qt Architect generated file ---

	File: FSPropGeneralData.h
	Last generated: Wed Oct 20 08:29:10 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CFSPropGeneralData_included
#define CFSPropGeneralData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qprogressbar.h>

class CFSPropGeneralData : public QWidget
{
    Q_OBJECT

public:

    CFSPropGeneralData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CFSPropGeneralData();

public slots:


protected slots:


protected:
    QLabel* m_IconLabel;
    QLabel* m_TypeLabel;
    QLabel* m_Type;
    QLabel* m_UsedSpaceLabel;
    QLabel* m_FreeSpaceLabel;
    QLabel* m_CapacityLabel;
    QLabel* m_FileSystemTypeLabel;
    QLabel* m_FileSystemType;
    QLabel* m_MountedFromLabel;
    QLabel* m_FileSystemPath;
    QProgressBar* m_Bar;
    QLabel* m_StatusLabel;
    QLabel* m_BarEndLabel;
    QLabel* m_Capacity1;
    QLabel* m_UsedSpace1;
    QLabel* m_FreeSpace1;
    QLabel* m_Capacity2;
    QLabel* m_UsedSpace2;
    QLabel* m_FreeSpace2;

};

#endif // CFSPropGeneralData_included
