/* Name: NetFilePropGeneralData.cpp

   Description: This file is a part of the Corel File Manager application.

   Author:	Oleg Noskov (olegn@corel.com)

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/

/*
 * NOTE: This source file was created using tab size = 2.
 * Please respect that setting in case of modifications.
 */


/**********************************************************************

	--- Qt Architect generated file ---

	File: NetFilePropGeneralData.cpp
	Last generated: Thu Feb 4 12:13:17 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "NetFilePropGeneralData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qframe.h>

CNetFilePropGeneralData::CNetFilePropGeneralData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	m_IconLabel = new QLabel( this, "Label_1" );
	m_IconLabel->setGeometry( 10, 10, 60, 40 );
	m_IconLabel->setMinimumSize( 0, 0 );
	m_IconLabel->setMaximumSize( 32767, 32767 );
	m_IconLabel->setFocusPolicy( QWidget::NoFocus );
	m_IconLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_IconLabel->setFontPropagation( QWidget::NoChildren );
	m_IconLabel->setPalettePropagation( QWidget::NoChildren );
	m_IconLabel->setText( "---" );
	m_IconLabel->setAlignment( 289 );
	m_IconLabel->setMargin( -1 );

	m_FileName = new QLabel( this, "Label_12" );
	m_FileName->setGeometry( 80, 20, 310, 20 );
	m_FileName->setMinimumSize( 0, 0 );
	m_FileName->setMaximumSize( 32767, 32767 );
	m_FileName->setFocusPolicy( QWidget::NoFocus );
	m_FileName->setBackgroundMode( QWidget::PaletteBackground );
	m_FileName->setFontPropagation( QWidget::NoChildren );
	m_FileName->setPalettePropagation( QWidget::NoChildren );
	m_FileName->setText( "---" );
	m_FileName->setAlignment( 289 );
	m_FileName->setMargin( -1 );

	QFrame* qtarch_Frame_4;
	qtarch_Frame_4 = new QFrame( this, "Frame_4" );
	qtarch_Frame_4->setGeometry( 10, 55, 464, 13 );
	qtarch_Frame_4->setMinimumSize( 0, 0 );
	qtarch_Frame_4->setMaximumSize( 32767, 32767 );
	qtarch_Frame_4->setFocusPolicy( QWidget::NoFocus );
	qtarch_Frame_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Frame_4->setFontPropagation( QWidget::NoChildren );
	qtarch_Frame_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_Frame_4->setFrameStyle( 52 );

	m_pFullNameLabel = new QLabel( this, "Label_13" );
	m_pFullNameLabel->setGeometry( 10, 75, 80, 20 );
	m_pFullNameLabel->setMinimumSize( 0, 0 );
	m_pFullNameLabel->setMaximumSize( 32767, 32767 );
	m_pFullNameLabel->setFocusPolicy( QWidget::NoFocus );
	m_pFullNameLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_pFullNameLabel->setFontPropagation( QWidget::NoChildren );
	m_pFullNameLabel->setPalettePropagation( QWidget::NoChildren );
	m_pFullNameLabel->setText( "---" );
	m_pFullNameLabel->setAlignment( 289 );
	m_pFullNameLabel->setMargin( -1 );

	m_FullName = new QLabel( this, "Label_15" );
	m_FullName->setGeometry( 100, 75, 375, 20 );
	m_FullName->setMinimumSize( 0, 0 );
	m_FullName->setMaximumSize( 32767, 32767 );
	m_FullName->setFocusPolicy( QWidget::NoFocus );
	m_FullName->setBackgroundMode( QWidget::PaletteBackground );
	m_FullName->setFontPropagation( QWidget::NoChildren );
	m_FullName->setPalettePropagation( QWidget::NoChildren );
	m_FullName->setText( "---" );
	m_FullName->setAlignment( 289 );
	m_FullName->setMargin( -1 );

	m_SizeLabel = new QLabel( this, "Label_16" );
	m_SizeLabel->setGeometry( 10, 105, 60, 18 );
	m_SizeLabel->setMinimumSize( 0, 0 );
	m_SizeLabel->setMaximumSize( 32767, 32767 );
	m_SizeLabel->setFocusPolicy( QWidget::NoFocus );
	m_SizeLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_SizeLabel->setFontPropagation( QWidget::NoChildren );
	m_SizeLabel->setPalettePropagation( QWidget::NoChildren );
	m_SizeLabel->setText( "---" );
	m_SizeLabel->setAlignment( 289 );
	m_SizeLabel->setMargin( -1 );

	m_Size = new QLabel( this, "Label_18" );
	m_Size->setGeometry( 100, 105, 375, 20 );
	m_Size->setMinimumSize( 0, 0 );
	m_Size->setMaximumSize( 32767, 32767 );
	m_Size->setFocusPolicy( QWidget::NoFocus );
	m_Size->setBackgroundMode( QWidget::PaletteBackground );
	m_Size->setFontPropagation( QWidget::NoChildren );
	m_Size->setPalettePropagation( QWidget::NoChildren );
	m_Size->setText( "---" );
	m_Size->setAlignment( 289 );
	m_Size->setMargin( -1 );

	m_pModifiedLabel = new QLabel( this, "Label_21" );
	m_pModifiedLabel->setGeometry( 10, 135, 60, 20 );
	m_pModifiedLabel->setMinimumSize( 0, 0 );
	m_pModifiedLabel->setMaximumSize( 32767, 32767 );
	m_pModifiedLabel->setFocusPolicy( QWidget::NoFocus );
	m_pModifiedLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_pModifiedLabel->setFontPropagation( QWidget::NoChildren );
	m_pModifiedLabel->setPalettePropagation( QWidget::NoChildren );
	m_pModifiedLabel->setText( "---" );
	m_pModifiedLabel->setAlignment( 289 );
	m_pModifiedLabel->setMargin( -1 );

	m_ModifyDate = new QLabel( this, "Label_22" );
	m_ModifyDate->setGeometry( 100, 135, 375, 20 );
	m_ModifyDate->setMinimumSize( 0, 0 );
	m_ModifyDate->setMaximumSize( 32767, 32767 );
	m_ModifyDate->setFocusPolicy( QWidget::NoFocus );
	m_ModifyDate->setBackgroundMode( QWidget::PaletteBackground );
	m_ModifyDate->setFontPropagation( QWidget::NoChildren );
	m_ModifyDate->setPalettePropagation( QWidget::NoChildren );
	m_ModifyDate->setText( "---" );
	m_ModifyDate->setAlignment( 289 );
	m_ModifyDate->setMargin( -1 );

	m_pAttributesLabel = new QLabel( this, "Label_23" );
	m_pAttributesLabel->setGeometry( 10, 165, 60, 20 );
	m_pAttributesLabel->setMinimumSize( 0, 0 );
	m_pAttributesLabel->setMaximumSize( 32767, 32767 );
	m_pAttributesLabel->setFocusPolicy( QWidget::NoFocus );
	m_pAttributesLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_pAttributesLabel->setFontPropagation( QWidget::NoChildren );
	m_pAttributesLabel->setPalettePropagation( QWidget::NoChildren );
	m_pAttributesLabel->setText( "---" );
	m_pAttributesLabel->setAlignment( 289 );
	m_pAttributesLabel->setMargin( -1 );

	m_Attributes = new QLabel( this, "Label_24" );
	m_Attributes->setGeometry( 100, 165, 375, 20 );
	m_Attributes->setMinimumSize( 0, 0 );
	m_Attributes->setMaximumSize( 32767, 32767 );
	m_Attributes->setFocusPolicy( QWidget::NoFocus );
	m_Attributes->setBackgroundMode( QWidget::PaletteBackground );
	m_Attributes->setFontPropagation( QWidget::NoChildren );
	m_Attributes->setPalettePropagation( QWidget::NoChildren );
	m_Attributes->setText( "---" );
	m_Attributes->setAlignment( 289 );
	m_Attributes->setMargin( -1 );

	resize( 489,350 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


CNetFilePropGeneralData::~CNetFilePropGeneralData()
{
}
