/* Name: SharePropGeneralData.h

   Description: This file is a part of the Corel File Manager application.

   Author:	Oleg Noskov (olegn@corel.com)

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/

/**********************************************************************

	--- Qt Architect generated file ---

	File: SharePropGeneralData.h
	Last generated: Sun Nov 28 21:42:34 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CSharePropGeneralData_included
#define CSharePropGeneralData_included

#include <qdialog.h>
#include <qlabel.h>

class CSharePropGeneralData : public QDialog
{
    Q_OBJECT

public:

    CSharePropGeneralData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CSharePropGeneralData();

public slots:


protected slots:


protected:
    QLabel* m_IconLabel;
    QLabel* m_Name;
    QLabel* m_pFullNameLabel;
    QLabel* m_FullName;
    QLabel* m_pCommentLabel;
    QLabel* m_Type;
    QLabel* m_pTypeLabel;
    QLabel* m_Comment;

};

#endif // CSharePropGeneralData_included
