/*
 * This file was generated by dbusidl2cpp version 0.4
 * when processing input file org.kde.MediaManager.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "mediamanageriface.h"

/*
 * Implementation of interface class OrgKdeMediaManagerInterface
 */

OrgKdeMediaManagerInterface::OrgKdeMediaManagerInterface(QDBusAbstractInterfacePrivate *p)
    : QDBusAbstractInterface(p)
{
}

OrgKdeMediaManagerInterface::~OrgKdeMediaManagerInterface()
{
}


#include "mediamanageriface.moc"
