/* Name: DiscconnectDlgData.h

   Description: This file is a part of the Corel File Manager application.

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/

/**********************************************************************

	--- Qt Architect generated file ---

	File: DisconnectDlgData.cpp
	Last generated: Mon Nov 29 18:42:50 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "DisconnectDlgData.h"

#define Inherited QDialog


CDisconnectDlgData::CDisconnectDlgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	m_List = new QListBox( this, "ListBox_1" );
	m_List->setGeometry( 10, 10, 306, 160 );
	m_List->setMinimumSize( 0, 0 );
	m_List->setMaximumSize( 32767, 32767 );
	m_List->setFocusPolicy( QWidget::StrongFocus );
	m_List->setBackgroundMode( QWidget::PaletteBase );
	m_List->setFontPropagation( QWidget::SameFont );
	m_List->setPalettePropagation( QWidget::SameFont );
	m_List->setFrameStyle( 51 );
	m_List->setLineWidth( 2 );
	m_List->setMidLineWidth( 0 );
	m_List->QFrame::setMargin( 0 );
	m_List->setDragSelect( TRUE );
	m_List->setAutoScroll( TRUE );
	m_List->setScrollBar( FALSE );
	m_List->setAutoScrollBar( TRUE );
	m_List->setBottomScrollBar( FALSE );
	m_List->setAutoBottomScrollBar( TRUE );
	m_List->setSmoothScrolling( TRUE );
	m_List->setMultiSelection( FALSE );
	m_List->setAutoUpdate( TRUE );

	m_pOKButton = new QPushButton( this, "PushButton_1" );
	m_pOKButton->setGeometry( 327, 10, 80, 26 );
	m_pOKButton->setMinimumSize( 80, 26 );
	m_pOKButton->setMaximumSize( 80, 26 );
	connect( m_pOKButton, SIGNAL(clicked()), SLOT(accept()) );
	m_pOKButton->setFocusPolicy( QWidget::TabFocus );
	m_pOKButton->setBackgroundMode( QWidget::PaletteBackground );
	m_pOKButton->setFontPropagation( QWidget::NoChildren );
	m_pOKButton->setPalettePropagation( QWidget::NoChildren );
	m_pOKButton->setText( "---" );
	m_pOKButton->setAutoRepeat( FALSE );
	m_pOKButton->setAutoResize( FALSE );
	m_pOKButton->setToggleButton( FALSE );
	m_pOKButton->setDefault( FALSE );
	m_pOKButton->setAutoDefault( TRUE );
	m_pOKButton->setIsMenuButton( FALSE );

	m_pCancelButton = new QPushButton( this, "PushButton_2" );
	m_pCancelButton->setGeometry( 327, 45, 80, 26 );
	m_pCancelButton->setMinimumSize( 80, 26 );
	m_pCancelButton->setMaximumSize( 80, 26 );
	connect( m_pCancelButton, SIGNAL(clicked()), SLOT(reject()) );
	m_pCancelButton->setFocusPolicy( QWidget::TabFocus );
	m_pCancelButton->setBackgroundMode( QWidget::PaletteBackground );
	m_pCancelButton->setFontPropagation( QWidget::NoChildren );
	m_pCancelButton->setPalettePropagation( QWidget::NoChildren );
	m_pCancelButton->setText( "---" );
	m_pCancelButton->setAutoRepeat( FALSE );
	m_pCancelButton->setAutoResize( FALSE );
	m_pCancelButton->setToggleButton( FALSE );
	m_pCancelButton->setDefault( FALSE );
	m_pCancelButton->setAutoDefault( FALSE );
	m_pCancelButton->setIsMenuButton( FALSE );

	resize( 418,180 );
	setMinimumSize( 418, 180 );
	setMaximumSize( 418, 180 );
}


CDisconnectDlgData::~CDisconnectDlgData()
{
}
