/* Name: CopyProgressDialogData.cpp

   Description: This file is a part of the CopyAgent.

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/

/**********************************************************************

	--- Qt Architect generated file ---

	File: CopyProgressDlgData.cpp
	Last generated: Mon Nov 29 00:57:03 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "CopyProgressDlgData.h"

#define Inherited QDialog


CCopyProgressDlgData::CCopyProgressDlgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 217088 )
{
	m_pCopyMovieLabel = new QLabel( this, "Label_1" );
	m_pCopyMovieLabel->setGeometry( 18, 18, 260, 40 );
	m_pCopyMovieLabel->setMinimumSize( 0, 0 );
	m_pCopyMovieLabel->setMaximumSize( 32767, 32767 );
	m_pCopyMovieLabel->setFocusPolicy( QWidget::NoFocus );
	m_pCopyMovieLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_pCopyMovieLabel->setFontPropagation( QWidget::NoChildren );
	m_pCopyMovieLabel->setPalettePropagation( QWidget::NoChildren );
	m_pCopyMovieLabel->setFrameStyle( 0 );
	m_pCopyMovieLabel->setLineWidth( 1 );
	m_pCopyMovieLabel->setMidLineWidth( 0 );
	m_pCopyMovieLabel->QFrame::setMargin( 0 );
	m_pCopyMovieLabel->setText( "" );
	m_pCopyMovieLabel->setAlignment( 289 );
	m_pCopyMovieLabel->setMargin( -1 );

	m_pTextLabel1 = new QLabel( this, "Label_2" );
	m_pTextLabel1->setGeometry( 18, 70, 480, 20 );
	m_pTextLabel1->setMinimumSize( 0, 0 );
	m_pTextLabel1->setMaximumSize( 32767, 32767 );
	m_pTextLabel1->setFocusPolicy( QWidget::NoFocus );
	m_pTextLabel1->setBackgroundMode( QWidget::PaletteBackground );
	m_pTextLabel1->setFontPropagation( QWidget::NoChildren );
	m_pTextLabel1->setPalettePropagation( QWidget::NoChildren );
	m_pTextLabel1->setFrameStyle( 0 );
	m_pTextLabel1->setLineWidth( 1 );
	m_pTextLabel1->setMidLineWidth( 0 );
	m_pTextLabel1->QFrame::setMargin( 0 );
	m_pTextLabel1->setText( "---" );
	m_pTextLabel1->setAlignment( 289 );
	m_pTextLabel1->setMargin( -1 );

	m_pTextLabel2 = new QLabel( this, "Label_3" );
	m_pTextLabel2->setGeometry( 18, 90, 480, 20 );
	m_pTextLabel2->setMinimumSize( 0, 0 );
	m_pTextLabel2->setMaximumSize( 32767, 32767 );
	m_pTextLabel2->setFocusPolicy( QWidget::NoFocus );
	m_pTextLabel2->setBackgroundMode( QWidget::PaletteBackground );
	m_pTextLabel2->setFontPropagation( QWidget::NoChildren );
	m_pTextLabel2->setPalettePropagation( QWidget::NoChildren );
	m_pTextLabel2->setFrameStyle( 0 );
	m_pTextLabel2->setLineWidth( 1 );
	m_pTextLabel2->setMidLineWidth( 0 );
	m_pTextLabel2->QFrame::setMargin( 0 );
	m_pTextLabel2->setText( "---" );
	m_pTextLabel2->setAlignment( 289 );
	m_pTextLabel2->setMargin( -1 );

	m_ByteProgress = new QProgressBar( 100, this, "ProgressBar_1" );
	m_ByteProgress->setGeometry( 60, 148, 335, 15 );
	m_ByteProgress->setMinimumSize( 0, 0 );
	m_ByteProgress->setMaximumSize( 32767, 32767 );
	m_ByteProgress->setFocusPolicy( QWidget::NoFocus );
	m_ByteProgress->setBackgroundMode( QWidget::PaletteBackground );
	m_ByteProgress->setFontPropagation( QWidget::NoChildren );
	m_ByteProgress->setPalettePropagation( QWidget::NoChildren );
	m_ByteProgress->setFrameStyle( 51 );
	m_ByteProgress->setLineWidth( 2 );
	m_ByteProgress->setMidLineWidth( 0 );
	m_ByteProgress->QFrame::setMargin( 0 );
	m_ByteProgress->setProgress( -1 );

	m_pCancelButton = new QPushButton( this, "PushButton_1" );
	m_pCancelButton->setGeometry( 408, 137, 79, 27 );
	m_pCancelButton->setMinimumSize( 0, 0 );
	m_pCancelButton->setMaximumSize( 32767, 32767 );
	connect( m_pCancelButton, SIGNAL(clicked()), SLOT(reject()) );
	m_pCancelButton->setFocusPolicy( QWidget::TabFocus );
	m_pCancelButton->setBackgroundMode( QWidget::PaletteBackground );
	m_pCancelButton->setFontPropagation( QWidget::NoChildren );
	m_pCancelButton->setPalettePropagation( QWidget::NoChildren );
	m_pCancelButton->setText( "Cancel" );
	m_pCancelButton->setAutoRepeat( FALSE );
	m_pCancelButton->setAutoResize( FALSE );
	m_pCancelButton->setToggleButton( FALSE );
	m_pCancelButton->setDefault( FALSE );
	m_pCancelButton->setAutoDefault( FALSE );
	m_pCancelButton->setIsMenuButton( FALSE );

	m_FileProgress = new QProgressBar( 100, this, "ProgressBar_3" );
	m_FileProgress->setGeometry( 60, 122, 335, 15 );
	m_FileProgress->setMinimumSize( 0, 0 );
	m_FileProgress->setMaximumSize( 32767, 32767 );
	m_FileProgress->setFocusPolicy( QWidget::NoFocus );
	m_FileProgress->setBackgroundMode( QWidget::PaletteBackground );
	m_FileProgress->setFontPropagation( QWidget::NoChildren );
	m_FileProgress->setPalettePropagation( QWidget::NoChildren );
	m_FileProgress->setFrameStyle( 51 );
	m_FileProgress->setLineWidth( 2 );
	m_FileProgress->setMidLineWidth( 0 );
	m_FileProgress->QFrame::setMargin( 0 );
	m_FileProgress->setProgress( -1 );

	m_FilesLabel = new QLabel( this, "Label_4" );
	m_FilesLabel->setGeometry( 18, 119, 39, 20 );
	m_FilesLabel->setMinimumSize( 0, 0 );
	m_FilesLabel->setMaximumSize( 32767, 32767 );
	m_FilesLabel->setFocusPolicy( QWidget::NoFocus );
	m_FilesLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_FilesLabel->setFontPropagation( QWidget::NoChildren );
	m_FilesLabel->setPalettePropagation( QWidget::NoChildren );
	m_FilesLabel->setFrameStyle( 0 );
	m_FilesLabel->setLineWidth( 1 );
	m_FilesLabel->setMidLineWidth( 0 );
	m_FilesLabel->QFrame::setMargin( 0 );
	m_FilesLabel->setText( "---" );
	m_FilesLabel->setAlignment( 289 );
	m_FilesLabel->setMargin( -1 );

	m_BytesLabel = new QLabel( this, "Label_6" );
	m_BytesLabel->setGeometry( 18, 144, 39, 20 );
	m_BytesLabel->setMinimumSize( 0, 0 );
	m_BytesLabel->setMaximumSize( 32767, 32767 );
	m_BytesLabel->setFocusPolicy( QWidget::NoFocus );
	m_BytesLabel->setBackgroundMode( QWidget::PaletteBackground );
	m_BytesLabel->setFontPropagation( QWidget::NoChildren );
	m_BytesLabel->setPalettePropagation( QWidget::NoChildren );
	m_BytesLabel->setFrameStyle( 0 );
	m_BytesLabel->setLineWidth( 1 );
	m_BytesLabel->setMidLineWidth( 0 );
	m_BytesLabel->QFrame::setMargin( 0 );
	m_BytesLabel->setText( "---" );
	m_BytesLabel->setAlignment( 289 );
	m_BytesLabel->setMargin( -1 );

	resize( 500,177 );
	setMinimumSize( 500, 177 );
	setMaximumSize( 500, 177 );
}


CCopyProgressDlgData::~CCopyProgressDlgData()
{
}
