/* Name: NewShareDialogData.h

   Description: This file is a part of the libmwn library.

   Author:	Oleg Noskov (olegn@corel.com)

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/

/*
 * NOTE: This source file was created using tab size = 2.
 * Please respect that setting in case of modifications.
 */

/**********************************************************************

	--- Qt Architect generated file ---

	File: NewShareDialogData.h
	Last generated: Thu Dec 10 08:45:15 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CNewShareDialogData_included
#define CNewShareDialogData_included

#include <qdialog.h>
#include <qbttngrp.h>
#include <qchkbox.h>
#include <qlined.h>
#include <qspinbox.h>
#include <qradiobt.h>
#include <qlabel.h>

class CNewShareDialogData : public QDialog
{
    Q_OBJECT

public:

    CNewShareDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CNewShareDialogData();

public slots:


protected slots:

    virtual void OnPermissions();

protected:
    QButtonGroup* m_ButtonGroup;
    QLineEdit* m_ShareName;
    QLineEdit* m_Comment;
    QRadioButton* m_MaximumAllowed;
    QRadioButton* m_Allow;
    QSpinBox* m_UsersMax;
    QCheckBox* m_Enabled;
		QLabel *m_pShareNameLabel;
		QLabel *m_pCommentLabel;
		QLabel *m_pUsersLabel;
		QPushButton *m_pOKButton;
		QPushButton *m_pCancelButton;
		QPushButton *m_pPermissionsButton;
};

#endif // CNewShareDialogData_included
