/* Name: resource.h

   Description: This file is a part of the libmwn library.

   Author:	Oleg Noskov (olegn@corel.com)

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License version 2 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.


*/


/*
 * NOTE: This source file was created using tab size = 2.
 * Please respect that setting in case of modifications.
 */

#ifndef __INC_RESOURCE_H__
#define __INC_RESOURCE_H__

#include <qmovie.h>
#include "common.h"

QTTEXTTYPE LoadString(int nID);

#define MWN_RESOURCE_START 1000

// String table

enum MWN_Strings
{
  knSTR_NEW_SHARE  = MWN_RESOURCE_START,
  knSTR_SHARE_DUP,
  knSTR_SHARE_DUP2,
  knSTR_ACCESS_THROUGH_SHARE,
  knSTR_FULL_CONTROL,
  knSTR_NO_ACCESS,
  knSTR_READ,
  knSTR_EVERYONE,
  knMOUNT_NETWORK_SHARE,
  knBROWSE_FOR_FOLDER,
  knUNABLE_TO_MOUNT,
  knMOUNT_POINT,
  knUNC_PATH,
  knENTER_UNC_PATH,
  knBAD_UNC_PATH,
  knYES,
  knNO,
  knBAD_PASSWORD,
  knCONNECT_AS,
  knPASSWORD,
  knOK,
  knCANCEL,
  knENTER_NETWORK_PASSWORD,
  knADD_USERS_AND_GROUPS,
  knENTER_USER_GROUP_NAME,
  knSTR_SHARE_TOOLONG,
  knENTER_MOUNT_POINT,
  knENTER_SHARE_NAME,
  knSTR_PREPARING_TO_COPY,
  knSTR_PREPARING_TO_MOVE,
  knSTR_COPYING,
  knSTR_MOVING,
  knSTR_FILE_MOVE,
  knSTR_FILE_COPY,
  knSTR_UNABLE_TO_OPEN_FOR_READING,
  knSTR_UNABLE_TO_OPEN_FOR_WRITING,
  knSTR_ERROR_WRITING_FILE,
  knSTR_ERROR_READING_FILE,
  knSTR_UNABLE_TO_REMOVE_FILE,
  knSTR_NO_PERMISSIONS,
  knSTR_CONFIRM_CREATE_DIRECTORY,
  knSTR_DIRECTORY,
  knSTR_UNABLE_TO_CREATE,
  knSTR_DESTINATION_FILE_EXISTS,
  knSTR_YES_ALL,
  knSTR_NO_ALL,
  knSTR_RETRY,
  knSTR_DONE,
  knSTR_REMAINING,
  knSTR_SECONDS_REMAINING,
  knSTR_UNABLE_TO_ESTABLISH_FTP_SESSION,
  knSTR_SERVER_NOT_FOUND,
  knFILENAME_CANNOT_CONTAIN,
  knSTR_RENAME,
  knSTR_YOU_MUST_TYPE_A_FILENAME,
  knUNABLE_TO_RENAME,
  knUNABLE_TO_RENAME_X_NOFILE,
  knX_NETWORK_PATH_NOT_FOUND,
  knBUILDING_FILE_LIST,
  knCONFIRM_FILE_REPLACE,
  knMODIFIED_ON_XXX,
  knSTR_DELETING,
  knSTR_PREPARING_TO_DELETE,
  knCONFIRM_MULTIPLE_FILE_DELETE,
  knCONFIRM_FOLDER_DELETE,
  knCONFIRM_FOLDER_REPLACE,
  knSTR_DESTINATION_FOLDER_EXISTS,
  knSTR_WINDOWS_NETWORK,
  knCONFIRM_FILE_DELETE_QUESTION,
  knCONFIRM_MULTIPLE_FILE_DELETE_QUESTION,
  knCONFIRM_FILE_DELETE,
  knCONFIRM_FOLDER_DELETE_QUESTION,
  knUNABLE_TO_DELETE,
  knUNABLE_TO_DELETE_X_NOFILE,
  knSTR_DELETE,
  knEFAULT,
  knEACCES,
  knENAMETOOLONG,
  knENOENT,
  knENOTDIR,
  knEISDIR,
  knENOMEM,
  knEROFS,
  knELOOP,
  knEIO,
  knSTR_NFS_NETWORK,
  knCANNOT_RENAME_X_Y,
  knERROR_RENAMING_FILE,
  knUNABLE_TO_RENAME_FILE_X,
  knSUPER_USER_RIGHTS,
  knPASSWORD_INVALID,
  knUNABLE_TO_MOUNT_X_Y,
  knMOUNT_X_FAILED,
  knCONFIRM_FOLDER_TO_TRASH_QUESTION,
  knCONFIRM_FILE_TO_TRASH_QUESTION,
  knDESTINATION_FOLDER_SAME,
  knDESTINATION_FOLDER_SUBTREE,
  knENOTEMPTY,
  knETXTBSY,
  knUNABLE_TO_CREATE_FOLDER,
  knCREATE_NEW_FOLDER,
  knECONNREFUSED,
  knREASON_GIVEN_BY_SERVER,
  knCONFIRM_MULTIPLE_FILE_TO_DUMPSTER_QUESTION,
  knSIZE_WARNING,
  knSIZE_WARNING_TEXT,
  knIGNORE,
  knABORT,
  knESCAPE_WARNING,
  knCONTINUE,
  knPRINTING,
  knFILE_REPLACE_DIALOG_TEXT_LABEL2,
  knFILE_REPLACE_DIALOG_TEXT_LABEL3,
  kn_YES,
  knYES_TO__ALL,
  kn_NO,
  knPRINTER_COLON,
  knCONNECT_AS_COLON,
  knSHARE_THIS_ITEM_AND_ITS_CONTENTS,
  knSHARE_NAME_COLON,
  knSTR_COMMENT_COLON,
  knSHARE_ENABLED,
  knNEW_SHARE_DOTDOTDOT,
  knREMOVE_SHARE,
  knUSER_LIMIT,
  knALLOW_ALL_USERS,
  knALLOW_MAXIMUM,
  knUSERS,
  kn_PERMISSIONS_DOTDOTDOT,
  knACCESS_THROUGH_SHARE,
  knNAME_COLON,
  knACCESS_TYPE_COLON,
  kn_ADD_DOTDOTDOT,
  kn_REMOVE,
  knSHARE_TO_MOUNT_COLON,
  knMOUNT_POINT_COLON,
  kn_BROWSE_DOTDOTDOT,
  kn_RECONNECT_AT_LOGON,
  knSHARED_DIRECTORIES_COLON,
  knFILES_COLON,
  knBYTES_COLON,
  knUSERS_AND_GROUPS,
  knUSER_COLON,
  knGROUP_COLON,
  knTYPE_OF_ACCESS_COLON,
  knUNABLE_TO_CREATE_SYMBOLIC_LINK_X,
  knCOPY_INSTEAD_QUESTION,
  knIGNORE_ALL,
  knENOSPC,
  knEEXIST,
  kn_SAVE,
  kn_OPEN,
  knSAVE_AS,
  knMY_COMPUTER,
  knNAME,
  knSIZE,
  knATTRIBUTES,
  knMODIFIED,
  knMOUNTED_ON,
  knFILESYSTEM,
  knTOTAL_SIZE,
  knFREE_SPACE,
  knCOMMENT,
  knORIGINAL_LOCATION,
  knDATE_DELETED,
  knOPEN,
  knMY_LINUX,
  knLOOK_IN_COLON,
  knSAVE_IN_COLON,
  knFILE__NAME_COLON,
  knFILES_OF__TYPE_COLON,
  knPASSWORDS_NOT_IDENTICAL,
  knERROR,
  knANONYMOUS_ACCESS,
  knALLOW_ACCESS_USING_THIS_PASSWORD_COLON,
  kn_CONFIRM_PASSWORD_COLON,
  knSHARE_ACCESS_DIALOG_TOP,
  knACCESS_TO_THIS_SHARE_IS_READONLY,
  knNFS_SHARING,
  kn_EDIT_DOTDOTDOT,
  knHOST,
  knPERMISSIONS,
  knOPTIONS,
  knPLEASE_ENTER_HOSTNAME,
  knADD_HOST_PERMISSIONS,
  knEDIT_HOST_PERMISSIONS,
  kn_HOST_COLON,
  kn_PERMISSIONS_COLON,
  kn_OPTIONS_COLON,
  knNO_SPACE_IN_NFS,
  knTYPE,
  knUNABLE_TO_MOUNT_NO_PRIVILEGES,
  knUNABLE_TO_MOUNT_NOMOUNTPOINT,
  knMOUNT_POINT_SPACES_NOT_ALLOWED,
  knSHARE_NAME_SPACES_NOT_ALLOWED,
  knLOCAL,
  knNETWORK_LPD,
  knUNKNOWN,
  knPRINTERS,
  knCONFIRM_ONE_ITEM_DELETE_QUESTION,
  knSKIP,
  knUNABLE_TO_READ_FILE,
  kn_DOMAIN_COLON,
  knCOPY_OF_SPACE,
  knXCOPY_N_OF_Y,
  knUNABLE_TO_MOVE_FROM_READONLY_FS,
  knSTR_PRINT,
	knCONFIRM_PRINTER_DELETE_QUESTION,
	knCONFIRM_PRINTER_DELETE,
	knSTR_FILE_PRINT,
	knRESTORING_NETWORK_CONNECTIONS_DOTDOTDOT,
	knCLOSING_NETWORK_CONNECTIONS_DOTDOTDOT,
	knSTR_CREATING_PRINT_JOB,
	knSTR_PREPARING_TO_CREATE_PRINT_JOB
};

//////////////////////////////////////////////////////////////////////

typedef enum
{
	keWorkgroupIcon=0,
	keIntranetIcon=1,
	keMyComputerIcon=2,
	keDesktopIcon=3,
	keLocalFileSystemIcon=4,
	keLocalFileSystemIconBig=5,
	keSharedLocalFileSystemIcon=6,
	keNetworkFileSystemIcon=7,
	keNetworkFileSystemIconBig=8,
	keCdromFileSystemIcon=9,
	keCdromFileSystemIconBig=10,
	keFloppyDriveIcon=11,
	keFloppyDriveIconBig=12,
	keWorldIcon=13,
	keUserFaceIcon=14,
	keUserGroupIcon=15,
	keServerIcon=16,
	keServerIconBig=17,
	keManyFilesIconBig=18,
	keMSRootIcon=19,
	keOpenFolderIcon=20,
	keClosedFolderIcon=21,
	keClosedFolderIconBig=22,
	keSharedFolderIcon=23,
	kePrinterIcon=24,
	kePrinterIconBig=25,
	keRegFileIcon=26,
	keRegFileIconBig=27,
	keDeviceIcon=28,
	keFIFOIcon=29,
	keProgIcon=30,
	keBrokenLinkIcon=31,
	keZipFileIcon=32,
	keWordPerfectFileIcon=33,
	keHeaderFileIcon=34,
	keCXXFileIcon=35,
	keHTMLFileIcon=36,
	keAudioFileIcon=37,
	keImageFileIcon=38,
	keReplaceFileIcon=39,
	keProgBigIcon=40,
	keZipFileBigIcon=41,
	keWordPerfectFileBigIcon=42,
	keHeaderFileBigIcon=43,
	keCXXFileBigIcon=44,
	keHTMLFileBigIcon=45,
	keAudioFileBigIcon=46,
	keImageFileBigIcon=47,
	keSharedFolderIconBig=48,
	keDeviceIconBig=49,
	keConfirmDeletePermanentIcon=50,
	keDrawFileIcon=51,
	keDrawFileIconBig=52,
	keReplaceFolderIcon=53,
	keHomeIcon=54,
	keBrokenLinkBigIcon=55,
	keWorkgroupIconBig=56,
	keMSRootIconBig=57,
	keWorldIconBig=58,
	keHomeIconBig=59,
	keMyComputerIconBig=60,
  keDumpsterIcon=61,
  keDumpsterIconBig=62,
	keNFSRootIcon=63,
	keNFSRootIconBig=64,
  kePrintersIcon=65,
  kePrintersIconBig=66,
  keNetworkPrinterIcon=67,
  keNetworkPrinterIconBig=68,
	keZIPDriveIcon=69,
	keZIPDriveIconBig=70
} CPixmapType;

extern QPixmap *gpLinkIcon;

extern QMovie *gpSearchMovie;
extern const int knSEARCH_MOVIE_WIDTH;
extern const int knSEARCH_MOVIE_HEIGHT;

QPixmap *LoadPixmap(CPixmapType type, BOOL bIsLink = FALSE, BOOL bIsHand = FALSE);
QPixmap *LoadCachePixmap(LPCSTR FileName);
void RegisterStringTable(int nFirstID, int nLastID, LPCSTR *pTable);

#endif /* __INC_RESOURCE_H__ */
